CREATE TABLE TBL_SELLERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    salary DOUBLE,
    gender INTEGER
);

INSERT
INTO TBL_SELLERS(NAME,SALARY,GENDER)
VALUES('Isaque',6000,1);          

INSERT
INTO TBL_SELLERS(NAME,SALARY,GENDER)
VALUES('Batista',1000,2);  

INSERT
INTO TBL_SELLERS(NAME,SALARY,GENDER)
VALUES('Barbosa',1200,1);  
